# Generated by Django 4.1 on 2022-09-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="shipping",
            field=models.ManyToManyField(to="shipping.shipping"),
        ),
    ]
