# Generated by Django 4.1 on 2022-09-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_alter_shipping_destination_alter_shipping_origin"),
        ("driver", "0003_alter_driver_shipping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="shipping",
        ),
        migrations.AddField(
            model_name="driver",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.shipping",
            ),
        ),
    ]
